### ISSUE TITLE
Map: be able to browse to a place when hovering 

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto-budgets-comparator#23]
When hovering a place in the map, and being shown the infowindow, we would need to let people browse to the place page. Possible ways: 

- Simple click on the polygon. Maybe it will make the panning of the map problematic
- A link in the infowindow; but we'd have to enable that the infowindow keeps being available. 

Thoughts @martgnz @ferblape ?

**Comment by martgnz** [comment]
I think that a click on the polygon would be more intuitive. Is there a way to distinguish between panning and clicking in Carto?

**Comment by furilo** [comment]
I guess if you don't release the click, the action is pan. Lets try with this and see. Can you do this or should we assign to @ferblape?

Other (future) paths to explore is to provide more content (evolution, other indicators) in the infowindow.

**Comment by martgnz** [comment]
I think that the Carto API sometimes is a bit different than Leaflet, so first I need to take a look at it.

**Comment by ferblape** [comment]
I´ll take care of this one, @martgnz, I appreciate your good intentions
