### ISSUE TITLE
Map: make the spinner more visible

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto-budgets-comparator#24]
It keeps feeling weird that when I click on a widget, nothing happens for a fews seconds until the screen reloads. Only the Carto spinner appears, but I think you don't see it. So as I think we commented, I'd: 

- [x] Show a complete black overlay of the map with opacity .2 or similar with a big spinner, to leave no doubt that new data is being loaded. 
- [x] Also, we need to change the cursor when hovering the widgets to communicate those are clickable.

cc @ferblape

**Comment by martgnz** [comment]
Ok. I will take a look at this!

**Comment by furilo** [comment]
Love it!
