### ISSUE TITLE
Map: color scheme

### ISSUE THREAD

**Issue by furilo** [PopulateTools/gobierto-budgets-comparator#25]
It feels a little bit strange to me using red and green (which is the most direct relation to bad and good) for expenses, inhabitants... Maybe we can choose a more neutral scheme?

@martgnz @ferblape

**Comment by martgnz** [comment]
Yeah, you're right. Some days ago I was trying other color sets. Tomorrow I will upload here a comparison so we can decide.

**Comment by furilo** [comment]
I'd just choose something neutral and see how it feels.
