### ISSUE TITLE
CSS issues in the maps template

### ISSUE THREAD

**Issue by ferblape** [PopulateTools/gobierto-budgets-comparator#7]
@martgnz there a couple of issues I need your help with in #4.  Please, use the branch `4-maps`, from PR #6 and commit there directly.

The first one is to fix the z-index of the year selector:

![screen shot 2016-11-28 at 17 27 28](https://cloud.githubusercontent.com/assets/17616/20676517/40d3e06e-b590-11e6-8b39-d6586b73bbe1.png)

The second one, which is the most important, is to position correctly the div `#map` to show the budget categories tree properly again in the left side column. 

![screen shot 2016-11-28 at 17 27 31](https://cloud.githubusercontent.com/assets/17616/20676552/63354cce-b590-11e6-967f-9c3de59c9ea4.png)

I'm using the template `app/views/gobierto_budgets/places/map.html.erb`. You can see a map in http://localhost:3000/places/santander/2016/map (only 2016 works).

**Comment by martgnz** [comment]
This should be fixed by now.
